[tool.pygbag]
name = "mangov3"
version = "0.1.0"
cdn = "https://pygame-web.github.io/archives/0.9/"
build_dir = "build/web"
assets = [
    "./assets/**",
    "./project.py",
    "./main.py"
]
icon = "favicon.png"
package = "web.pygame.mangov3"
