-- Tracks Mango's state
CREATE TABLE IF NOT EXISTS mango_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hunger INTEGER NOT NULL CHECK(hunger BETWEEN 0 AND 100),
    happiness INTEGER NOT NULL CHECK(happiness BETWEEN 0 AND 100),
    cleanliness INTEGER NOT NULL CHECK(cleanliness BETWEEN 0 AND 100),
    energy INTEGER NOT NULL CHECK(energy BETWEEN 0 AND 100),
    health INTEGER NOT NULL CHECK(health BETWEEN 0 AND 100),
    age INTEGER NOT NULL DEFAULT 0,
    last_updated TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Scores from Flappy Mango
CREATE TABLE IF NOT EXISTS scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    score INTEGER NOT NULL,
    played_at TEXT DEFAULT CURRENT_TIMESTAMP
);
