name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
                  pip install pytest pygbag playwright || true

            - name: Build web package
              env:
                  SDL_VIDEODRIVER: dummy
              run: |
                  set -e
                  pip install pygbag || true
                  if python -c "import pygbag" 2>/dev/null; then
                    python -m pygbag --build --package dist/pygbag main.py || python package_web.py --simulate --output dist/pygbag
                  else
                    python package_web.py --simulate --output dist/pygbag
                  fi

            - name: Install Playwright browsers
              run: |
                  python -m playwright install chromium

            - name: Run tests
              env:
                  SDL_VIDEODRIVER: dummy
              run: |
                  pytest -q

            - name: Upload web build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: pygbag-build
                  path: |
                      build/web
                      dist/pygbag
